 [theme]
baseFontSize = 17

primaryColor = "#FFFFFF"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#c1d2ff"
textColor = "#0a0a0a"
font = "Spectral:https://fonts.googleapis.com/css2?family=Spectral:wght@400;600;700&display=swap"

